stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: "registry.gitlab.com/babyhelm/babyhelm"

build-dev:
  stage: build
  image: docker:dind
  services:
    - docker:dind
  script:
    - docker info
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA-dev .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA-dev

unit-tests:
  stage: test
  image: $IMAGE_NAME:$CI_COMMIT_SHORT_SHA-dev
  script:
    - make unit-test

deploy-dev:
  stage: deploy
  script:
    - echo "Deploying to dev..." # TODO