"""add_application_image

Revision ID: 46602c7f481c
Revises: 69ae9c88ccdc
Create Date: 2024-06-22 13:53:29.947459

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46602c7f481c"
down_revision: Union[str, None] = "69ae9c88ccdc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("applications", sa.Column("image", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "image")
    # ### end Alembic commands ###
