apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-configmap
  labels:
    app: {{ .Values.app.name }}
data:
  {{ .Values.app.config.file }}: |-
      debug: True
      database:
        url: {{ .Values.env.database_url }}
        echo: True
        expire_on_commit: False
      templates:
        path: "babyhelm/templates"
      auth:
        access_token_expire_minutes: 30
        refresh_token_expire_days: 30
        secret_key: {{ .Values.env.password_secret_key }}
      kubeconfig:
        path: "local/kubeconfig.yaml"
