---
debug: True
database:
  url: "postgresql+asyncpg://postgres:postgres@localhost:5432/postgres"
  echo: True
  expire_on_commit: False
templates:
  path: "babyhelm/templates"
auth:
  access_token_expire_minutes: 30
  refresh_token_expire_days: 30
cubeconfig:
  path: "local/kubeconfig.yaml"
