---
debug: True
database:
  url: "postgresql+asyncpg://postgres:postgres@localhost:5432/postgres"
  echo: True
  expire_on_commit: False
templates:
  path: "babyhelm/templates"
kubeconfig:
  path: "local/kubeconfig.yaml"
