---
debug: True
database:
  url: "postgresql+asyncpg://postgres:postgres@localhost:5432/babyhelm"
  echo: True
  expire_on_commit: False
templates:
  path: "babyhelm/templates"
auth:
  secret_key: "chipinkos"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 30
kubeconfig:
  path: "local/kubeconfig.yaml"
host_postfix: "svc.taila53571.ts.net"
