app:
  name: api
  deployment:
    postfix: deployment
    replicas: 2
    image: registry.gitlab.com/babyhelm/babyhelm:latest
    port: 8000
  service:
    postfix: svc
    type: LoadBalancer
    loadBalancerClass: tailscale
    ports:
      port: 80
      targetPort: 8000
